retrieve_task:
  description: >
    Navigate to the specified local Git repository using the {repo_path} provided by the user. 
    Check out the {branch} to ensure you are accessing the correct version of the code. 
    Search the entire repository for all files ending with the .java extension.
  expected_output: >
    All .java file paths from the specified {branch} of the local Git repository using Git Document Loader tool. 
    The output should be well-organized, with no duplicates or irrelevant files, and formatted to be easily used by another agent.
  agent: retrieval_agent

fix_task:
  description: >
    Use the list of .java files from the retrieval agent to analyze the current Java source code. 
    Identify and fix discrepancies between the {actual_result} produced by the code and the {expected_result} expected. 
    Implement code modifications to resolve the issues, ensuring the changes address the root cause of the bugs. 
    Revise the result and ensure the results match the expected behavior.
  expected_output: >
    A Git diff file that shows all the changes made to the Java code, highlighting modified, added, or deleted lines. 
    The output should be formatted clearly, making it easy for the user to review and apply the bug fixes in their repository.
    Output git diff file should be saved to the diff.txt file. Don't save the final result text, only the diff
  agent: fixing_agent