retrieve_task:
  description: >
    Navigate to the specified local Git repository using the {repo_path} provided by the user. 
    Check out the {branch} to ensure you are accessing the correct version of the code. 
    Search the entire repository for all files ending with the .java extension.
  expected_output: >
    All .java file paths from the specified {branch} of the local Git repository using Git Document Loader tool. 
    The output should be well-organized, with no duplicates or irrelevant files, and formatted to be easily used by another agent.
  agent: retrieval_agent

develop_task:
  description: >  
    Use the source code provided by the `retrieval_agent` to address the task described in {task_description}.  
    Analyze the existing codebase, make the required modifications, and generate a `git diff` file that reflects the changes.
  expected_output: >  
    A complete `git diff` file containing all code modifications made to implement the task described in {task_description}.  
    The diff should be clean, well-documented, and compatible with the existing codebase, ensuring no errors or inconsistencies. 
    It should not contain any unnecessary or irrelevant changes or comments that are not relevant to the task.
  agent: developer_agent