retrieve_task:
  description: >
    Используй Git Document Loader для поиска в репозитории и извлечения всех файлов с расширениями .java, .kt, .py, .sql, .yaml, .yml, .xml, .html, .css, .js
  expected_output: >
    Полный и хорошо организованный список всех путей к файлам с расширениями .java, .kt, .py, .sql, .yaml, .yml, .xml, .html, .css, .js из указанной ветки {branch} локального репозитория Git.
    Вывод должен исключать дубликаты или нерелевантные файлы и должен быть отформатирован так, чтобы следующий агент мог легко им воспользоваться.
  agent: retrieval_agent

fix_task:
  description: >
    Используй список файлов, предоставленный агентом по извлечению, чтобы проанализировать текущий исходный код. 
    Определи различия между {actual_result}, генерируемым существующим кодом, и {expected_result}. 
    Внеси необходимые изменения в код, чтобы устранить проблемы, убедившись, что эти изменения устраняют основную причину ошибок. 
    Проверь, что обновленный код дает результаты, соответствующие ожидаемому поведению.
  expected_output: >
    Файл git diff, который фиксирует все изменения, внесенные в код на Java, четко выделяя измененные, добавленные или удаленные строки. 
    Выходной результат должен быть хорошо структурированным и удобным для просмотра пользователем, чтобы он мог применить исправления в своем репозитории. 
    Сохрани git diff в файл с именем diff.txt.
  agent: fixing_agent
