fix_task:
  description: >
    Read the following text representation of a project - {local_repository_content}
    
    Use the content by the local_repository_content to analyze the current Java or Kotlin source code. 
    Identify and fix discrepancies between the {actual_result} produced by the code and the {expected_result} expected. 
    Implement code modifications to resolve the issues, ensuring the changes address the root cause of the bugs. 
    Revise the result and ensure the results match the expected behavior.
  expected_output: >
    A Git diff file that shows all the changes made to the Java code, highlighting modified, added, or deleted lines. 
    The output should be formatted clearly, making it easy for the user to review and apply the bug fixes in their repository.
    Output git diff file should be saved to the diff.txt file.
  agent: fixing_agent