retrieve_task:
  description: >
    Используй Git Document Loader для поиска в репозитории и извлечения всех файлов с расширениями .java, .kt, .py, .sql, .yaml, .yml, .xml, .html, .css, .js
  expected_output: >
    Полный и хорошо организованный список всех путей к файлам с расширениями .java, .kt, .py, .sql, .yaml, .yml, .xml, .html, .css, .js из указанной ветки {branch} локального репозитория Git.
    Вывод должен исключать дубликаты или нерелевантные файлы и должен быть отформатирован так, чтобы следующий агент мог легко им воспользоваться.
  agent: retrieval_agent

develop_task:
  description: >
    Используй исходный код, предоставленный `retrieval_agent`, чтобы выполнить задачу, описанную в {task_description}. 
    Проанализируй существующую кодовую базу, внеси необходимые изменения и сгенерируй файл `git diff`, отражающий внесенные изменения.
  expected_output: >
    Полный файл `git diff`, содержащий все модификации кода, сделанные для выполнения задачи, описанной в {task_description}. 
    Разница должна быть чистой, хорошо задокументированной и совместимой с существующей кодовой базой, гарантирующей отсутствие ошибок или несоответствий. 
    Она не должна содержать ненужных или несущественных изменений или комментариев, не относящихся к задаче.
  agent: developer_agent