python_filename: custom_gigachat_api.py
custom_handler_instance_name: gigachat_custom_llm
custom_handler: custom_gigachat_api.gigachat_custom_llm

gigachat_settings:
  auth_url: "https://ngw.devices.sberbank.ru:9443/api/v2/oauth"
  base_url: "https://gigachat.devices.sberbank.ru/api/v1"
  verify_ssl: false
  scope: "GIGACHAT_API_PERS"

model_list:
  - model_name: "gigachat-custom-model"
    litellm_params:
      model: "gigachat-custom-llm/gigachat-model"

litellm_settings:
  custom_provider_map:
    - {"provider": "gigachat-custom-llm", "custom_handler": custom_gigachat_api.gigachat_custom_llm}